reportportal/service-api

- CHANGELOG.md
- src/main/java/com/epam/ta/reportportal/core/externalsystem/ExternalSystemEurekaDelegate.java
* EPMRPP-20925 - Error is a bit incorrect, If BTS is not up and user tries to post bug to the system
* EPMRPP-20906 - Incorrect message from ws in case user tryes to submit BTS that does not enabled
> fix external system errors

- build.gradle
- src/main/java/com/epam/ta/reportportal/core/item/FinishTestItemHandlerImpl.java
- src/main/java/com/epam/ta/reportportal/core/launch/impl/RetriesLaunchHandler.java
According to TestNG specialty of items current invocation counting in multithreading launch
should be added another check on item's finish. Also it is not really need to hide the statistics while retries are running. It is recalculated on the launch's finish.
> Introduce retry flag on item's finish. 

- src/main/java/com/epam/ta/reportportal/core/item/UpdateTestItemHandlerImpl.java
AutoAnalyzed flag will depend on data, that was received from Client, instead of always being "false". If no data received from Client, flag will be "false" by default.
https://github.com/reportportal/reportportal/issues/427
> AutoAnalyzed flag fix

- build.gradle
- src/main/resources/application.properties
- src/main/resources/application.yaml
Add default configurations for `datastore.minio.bucketPrefix` and `datastore.minio.defaultBucketName`.
Allows to fix https://github.com/reportportal/service-api/issues/1196 and https://github.com/reportportal/kubernetes/issues/115
> #1196 Add minio bucket configuration properties

- src/main/java/com/epam/ta/reportportal/core/configs/Swagger2Configuration.java
Refer `service-authorization` PR # [91](https://github.com/reportportal/service-authorization/pull/91)
This change is somehow missed in `service-api`. Because of which, basePath is populated as blank when running in kubernetes.
> Swagger: add base path

- src/main/java/com/epam/ta/reportportal/util/email/EmailService.java
https://jiraeu.epam.com/browse/EPMRPP-86542
* ClassPathResource usage is not applicable when classes loaded by URLClassLoader. Unified approach used instead
Succesfully verified against local environment after applying the fix
> EPMRPP-86542 || fixed loading resources for email

- src/main/java/com/epam/ta/reportportal/core/configs/Swagger2Configuration.java
- src/main/resources/application.yaml
By using it, we can prevent the duplication of names in the Swagger host path like this: `/api/api`
> EPMRPP-86945 ||Check application name into Swagger base-path

- src/main/java/com/epam/ta/reportportal/core/imprt/ImportLaunchHandlerImpl.java
- src/test/java/com/epam/ta/reportportal/core/imprt/ImportLaunchHandlerImplTest.java
no need to implement custom logic for launch name since it is already implemented here:
https://github.com/reportportal/service-api/blob/develop/src/main/java/com/epam/ta/reportportal/core/imprt/impl/XmlImportStrategy.java#L64C58-L64C58
and here:
https://github.com/reportportal/service-api/blob/develop/src/main/java/com/epam/ta/reportportal/core/imprt/impl/ZipImportStrategy.java#L71
and the result saved into launch table
> EPMRPP-86742 || launch name fix

- src/main/java/com/epam/ta/reportportal/health/JobsHealthIndicator.java
- src/main/java/com/epam/ta/reportportal/info/JobsInfoContributor.java
- src/main/resources/application.yaml
In order to show detailed health information, the property `management.endpoint.health.show-details=always`
should be set in `application.properties` for both `service-api` and `jobs-service` projects
> EPMRPP-86812 || extended actuator with "jobs" module info

- src/main/java/com/epam/ta/reportportal/core/remover/user/UserPhotoRemover.java
Impossible to process attachments in data storage because of already removed references in user storage
No need to remove these properties twice
Another solution, deep copy of user object could be passed as the parameter here https://github.com/reportportal/service-api/blob/develop/src/main/java/com/epam/ta/reportportal/core/user/impl/DeleteUserHandlerImpl.java#L120
> EPMRPP-87382 fixed user attachments double removal

- src/main/java/com/epam/ta/reportportal/core/configs/SpringDocConfiguration.java
- src/main/java/com/epam/ta/reportportal/util/SchemaFactory.java
…PI tab in "API Documentation" page
> EPMRPP-89678 || Filter parameters are missing for some endpoints on API tab in "API Documentation" page

- project-properties.gradle
- src/main/java/com/epam/ta/reportportal/core/launch/StopLaunchHandler.java
- src/main/java/com/epam/ta/reportportal/core/launch/impl/StopLaunchHandlerImpl.java
- src/main/java/com/epam/ta/reportportal/ws/controller/LaunchController.java
- src/test/java/com/epam/ta/reportportal/core/launch/impl/FinishLaunchHandlerImplTest.java
…nish launch email in case launch has status 'stopped'
> EPMRPP-90342 || Email notifications. Broken links are displayed in finish launch email in case launch has status 'stopped'

- build.gradle
- src/main/java/com/epam/ta/reportportal/util/ControllerUtils.java
- src/main/java/com/epam/ta/reportportal/util/OffsetRequest.java
- api specification updated
- implemented offset-based pagination
> EPMRPP-93783 offset-based paging

- src/main/java/com/epam/ta/reportportal/core/integration/util/EmailServerIntegrationService.java
- src/main/java/com/epam/ta/reportportal/util/email/EmailService.java
Change SMTP integration logic:
- For SMTP we use a value from the from field. We don't use a username for it.
- For sending a test connection email we use an address from the from field.
- For old integrations, keep using the username if a from value is not valid or exists.
> Adjust email recipient in sendConnectionTestEmail

- build.gradle
Fix critical [CVE-2021-43113](https://github.com/advisories/GHSA-gv87-q66h-4277) for com.lowagie:itext:4.2.2
> 5.13.1 hotfix release 

- src/main/java/com/epam/ta/reportportal/core/project/impl/DeleteProjectHandlerImpl.java
The change reorders the call to `projectContentRemover.remove(project)` to occur after several other operations have been completed.
> EPMRPP-100435 || fix transactions order

- build.gradle
- src/main/java/com/epam/ta/reportportal/core/integration/plugin/impl/CreatePluginHandlerImpl.java
- src/main/java/com/epam/ta/reportportal/core/integration/plugin/strategy/PluginUploaderFactory.java
- src/test/java/com/epam/ta/reportportal/core/integration/plugin/impl/strategy/PluginUploaderFactoryTest.java
- src/test/java/com/epam/ta/reportportal/core/integration/plugin/strategy/PluginUploaderFactoryTest.java
This pull request refactors the plugin upload handling logic to use file extensions instead of MIME content types, simplifying the mapping of plugins to their respective uploaders. The changes include updates to the `PluginUploaderFactory` class, its methods, and related tests.
* **Updated `PluginUploaderFactory` to map file extensions instead of MIME content types**:
- Replaced MIME type keys (e.g., `application/java-archive`) with file extensions (e.g., `jar`, `zip`, `json`) in the `uploads` map.
- Modified the `getUploader` method to accept file extensions instead of content types and updated error messages accordingly.
* **Refactored `CreatePluginHandlerImpl` to extract file extensions**:
- Added usage of `FilenameUtils.getExtension` to determine the file extension of the uploaded …
> Refactor plugin uploader to use file extensions instead of content types

- src/main/java/com/epam/ta/reportportal/core/integration/plugin/impl/PluginLoaderImpl.java
This pull request refines the `convertToDetails` method in `PluginLoaderImpl.java` to improve null safety and avoid adding empty values to the `details` map. The most important change is the replacement of direct `put` calls with conditional checks using `Optional` to ensure only non-empty values are added.
Code improvements for null safety and data validation:
* [`src/main/java/com/epam/ta/reportportal/core/integration/plugin/impl/PluginLoaderImpl.java`](diffhunk://#diff-5f61342761b599a9496cb199ad40426c77b79ade6134cc564979f3e09a3c18e9L209-R217): Updated the `convertToDetails` method to use `Optional.ofNullable` with `filter` to check for non-empty values before adding `metadata`, `properties`, and `binaryData` to the `details` map. This prevents null or empty values from being included.
> Refactor plugin data handling to include optional metadata, properties, and binary data

- src/main/java/com/epam/ta/reportportal/ws/controller/GeneratedProjectController.java
- src/main/java/com/epam/ta/reportportal/ws/controller/GroupController.java
This pull request introduces updates to permission annotations in the `GeneratedProjectController` and `GroupController` classes, along with a submodule update in the `api-registry`. The key changes include replacing the `IS_ADMIN` permission with more granular permissions and updating the submodule reference.
* `GeneratedProjectController.java`:
- Replaced `@PreAuthorize(IS_ADMIN)` with `@PreAuthorize(ALLOWED_TO_VIEW_PROJECT)` for the `getGroupsOfProject` and `getProjectGroupById` methods, enabling view-level permissions. [[1]](diffhunk://#diff-f9b98e7f1fab8d2c605175eab01c8648abbad4416bcddbdfbecfd383d8a1d47bL40-R41) [[2]](diffhunk://#diff-f9b98e7f1fab8d2c605175eab01c8648abbad4416bcddbdfbecfd383d8a1d47bL51-R52)
- Replaced `@PreAuthorize(IS_ADMIN)` with …
> Fix project groups permissions

- build.gradle
- gradle.properties
- gradle/libs.versions.toml
- settings.gradle
This pull request introduces significant changes to dependency management and versioning in the project. It centralizes dependency versions in a new `gradle/libs.versions.toml` file, removes hardcoded versions from `gradle.properties`, and updates the Gradle settings to enforce repository usage policies.
* **Centralized Dependency Versions**: Introduced a `gradle/libs.versions.toml` file to manage all dependency versions, including libraries, plugins, and platforms. This improves maintainability and ensures consistency across the project.
* **Removed Hardcoded Versions**: Removed hardcoded dependency versions (`lombokVersion`, `springBootVersion`, etc.) from `gradle.properties`, as these are now managed in the `libs.versions.toml` file.
* **Repository Management**: Updated …
> Refactor build.gradle to use version catalog for dependencies

- build.gradle
- src/main/java/com/epam/ta/reportportal/core/integration/plugin/strategy/JsonPluginUploader.java
- src/test/java/com/epam/ta/reportportal/plugin/JsonPluginUploaderTest.java
This pull request refactors the `JsonPluginUploader` class to adjust the plugin upload flow.
* **Improved handling of existing plugins:** The `uploadPlugin` method now checks if a plugin with the same name already exists in the repository. If it does, the plugin's ID is updated before saving, ensuring proper handling of updates. (`[src/main/java/com/epam/ta/reportportal/core/integration/plugin/strategy/JsonPluginUploader.javaL78-R82](diffhunk://#diff-3d194ff72d32e6c7815e79269308748d8aa4da603fe5a8a15792a4b131ac37b9L78-R82)`)
> Refactor plugin upload logic to improve manifest persisting

- gradle/libs.versions.toml
This PR upgrades commons-dao to include a fix that restores the orgs_user_id filter
> EPMRPP-106884 Upgrade commons-dao: restore org_user_id filter

- build.gradle
- gradle/libs.versions.toml
- src/main/java/com/epam/ta/reportportal/core/organization/OrganizationExtensionPoint.java
- src/main/java/com/epam/ta/reportportal/exception/rest/StatusCodeMapping.java
- src/main/java/com/epam/ta/reportportal/ws/controller/GeneratedProjectController.java
- src/main/java/com/epam/ta/reportportal/ws/controller/GroupController.java
- src/main/java/com/epam/ta/reportportal/ws/controller/OrganizationController.java
- src/main/java/com/epam/ta/reportportal/ws/controller/OrganizationGroupController.java
This pull request refactors error handling across several controllers and extension points in the codebase, standardizing the use of `ReportPortalException` and custom `ErrorType` enums instead of generic Spring exceptions. The changes improve consistency in error reporting, especially for cases involving missing resources and paid plugin requirements. Additionally, the HTTP status mapping is updated to support new error types related to payment requirements.
**Error handling standardization:**
* Replaced all usages of `ResponseStatusException` with `ReportPortalException`, passing in appropriate `ErrorType` values such as `NOT_FOUND` and `PAID_PLUGIN_REQUIRED` in controllers like `GroupController`, `GeneratedProjectController`, `OrganizationController`, and `OrganizationGroupController`. …
> EPMRPP-107161 || Error types for plugin exception
