reportportal/service-api

CHANGELOG.md
build.gradle
src/main/java/com/epam/ta/reportportal/core/project/impl/DeleteProjectHandler.java

* EPMRPP-22340 - API: It's possible to delete project with entryType=UPSA

fix:It's possible to delete project with entryType=UPSA

---

CHANGELOG.md
build.gradle
src/main/java/com/epam/ta/reportportal/core/item/StartTestItemHandlerImpl.java

Update only one field of parent item instead of updating whole document

fix reportportal/reportportal#9

---

src/main/java/com/epam/ta/reportportal/migration/ChangeSets_3_0.java
src/main/resources/migration/v3_0_0_2.js
src/main/resources/spring-demo-data.xml
src/test/java/com/epam/ta/reportportal/ws/controller/impl/SettingsControllerTest.java

added tests for controller of analytics settings

migrated db to different names in serverSettings

---

src/main/java/com/epam/ta/reportportal/core/item/TestItemUniqueIdGenerator.java
src/main/java/com/epam/ta/reportportal/core/item/UpdateUniqueId.java
src/main/java/com/epam/ta/reportportal/migration/ChangeSets_3_3.java
src/test/java/com/epam/ta/reportportal/core/item/UniqueIdGeneratorTest.java

* migrate uniqueId to md5 instead of base64
* renamed set

Md5 (#209)

---

CHANGELOG.md
src/main/java/com/epam/ta/reportportal/core/item/StartTestItemHandlerImpl.java
src/main/java/com/epam/ta/reportportal/core/launch/impl/GetLaunchHandler.java
src/main/java/com/epam/ta/reportportal/core/widget/content/GeneralFilterStrategy.java

Fixes  
EPMRPP-33083 - WS: The extra statistics is returned for No Defects for Comparison launches
EPMRPP-32107 - WS: Unclassified error on load widget in case the filter deleted
EPMRPP-32107 - WS: Unclassified error on load widget in case the filter deleted

fix comparing counting

---

src/main/java/com/epam/ta/reportportal/core/configs/MvcConfig.java
src/main/java/com/epam/ta/reportportal/core/configs/SecurityConfiguration.java

* allow all origins
* set allowed methods
* allow send auth header
By applying these changes following issue is fixed: https://github.com/reportportal/service-api/issues/296

Add CORS configuration

---

build.gradle
src/main/java/com/epam/ta/reportportal/core/annotation/Datastore.java
src/main/java/com/epam/ta/reportportal/core/log/impl/CreateLogHandler.java
src/main/java/com/epam/ta/reportportal/store/database/BinaryData.java
src/main/java/com/epam/ta/reportportal/store/database/entity/log/Log.java
src/main/java/com/epam/ta/reportportal/store/filesystem/DataStore.java
src/main/java/com/epam/ta/reportportal/store/filesystem/LocalDataStore.java
src/main/java/com/epam/ta/reportportal/store/filesystem/LocalFilePathGenerator.java
src/main/java/com/epam/ta/reportportal/store/filesystem/distributed/SeaweedDataStore.java
src/main/java/com/epam/ta/reportportal/ws/converter/builders/LogBuilder.java
src/main/resources/application.properties
src/test/java/com/epam/ta/reportportal/store/filesystem/LocalDataStoreTest.java
src/test/java/com/epam/ta/reportportal/store/filesystem/LocalFileNameGeneratorTest.java
src/test/java/com/epam/ta/reportportal/store/filesystem/distributed/SeaweedDataStoreTest.java
src/test/resources/test-application.properties

Added simple implementations of data stores
- LocalDataStore - store files locally
- SeaweedDataStore - store files in seaweed fs

Ps migrations filestorage

---

src/main/java/com/epam/ta/reportportal/core/item/FinishTestItemHandlerImpl.java

Now flag will be set depending on the Client request data.

Auto analyzed flag after finishing test item fix.

---

src/main/java/com/epam/ta/reportportal/core/configs/SchedulerConfiguration.java
src/main/java/com/epam/ta/reportportal/core/jasper/TestItemPojo.java
src/main/java/com/epam/ta/reportportal/events/handler/AddDemoProjectEventHandler.java
src/main/java/com/epam/ta/reportportal/info/JobSchedulerInfoContributor.java
src/main/java/com/epam/ta/reportportal/job/FlushingDataJob.java
src/main/resources/application.properties
src/main/resources/templates/report/report.jrxml

merge to master 4.3.1

---

src/main/java/com/epam/ta/reportportal/demodata/Attachment.java
src/main/java/com/epam/ta/reportportal/demodata/AttachmentMetaData.java
src/main/java/com/epam/ta/reportportal/demodata/ContentUtils.java
src/main/java/com/epam/ta/reportportal/demodata/DefaultDemoDataFacade.java
src/main/java/com/epam/ta/reportportal/demodata/DemoDashboardsService.java
src/main/java/com/epam/ta/reportportal/demodata/DemoDataCommonService.java
src/main/java/com/epam/ta/reportportal/demodata/DemoDataController.java
src/main/java/com/epam/ta/reportportal/demodata/DemoDataFacade.java
src/main/java/com/epam/ta/reportportal/demodata/DemoDataRq.java
src/main/java/com/epam/ta/reportportal/demodata/DemoDataRs.java
src/main/java/com/epam/ta/reportportal/demodata/DemoDataService.java
src/main/java/com/epam/ta/reportportal/demodata/DemoLogsService.java

De data with handlers

---

build.gradle
src/main/java/com/epam/ta/reportportal/core/events/activity/WidgetUpdatedEvent.java
src/main/java/com/epam/ta/reportportal/core/widget/content/LoadContentStrategy.java
src/main/java/com/epam/ta/reportportal/core/widget/content/filter/LaunchHistoryFilterStrategy.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/ActivityContentLoader.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/BugTrendChartContentLoader.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/CasesTrendContentLoader.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/ChartInvestigatedContentLoader.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/CumulativeTrendChartLoader.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/FlakyCasesTableContentLoader.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/LaunchStatisticsChartContentLoader.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/LaunchesComparisonContentLoader.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/LaunchesDurationContentLoader.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/LaunchesTableContentLoader.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/LineChartContentLoader.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/MostTimeConsumingContentLoader.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/NotPassedTestsContentLoader.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/OverallStatisticsContentLoader.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/PassingRatePerLaunchContentLoader.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/PassingRateSummaryContentLoader.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/ProductStatusFilterGroupedContentLoader.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/ProductStatusLaunchGroupedContentLoader.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/TopTestCasesContentLoader.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/UniqueBugContentLoader.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/util/ProductStatusContentLoaderManager.java
src/main/java/com/epam/ta/reportportal/core/widget/impl/UpdateWidgetHandlerImpl.java
src/main/java/com/epam/ta/reportportal/core/widget/util/WidgetOptionUtil.java
src/main/java/com/epam/ta/reportportal/ws/converter/builders/WidgetBuilder.java
src/main/java/com/epam/ta/reportportal/ws/converter/converters/WidgetConverter.java
src/test/java/com/epam/ta/reportportal/core/widget/util/WidgetOptionUtilTest.java

Content loaders refactoring.
Widget option util class has been added.

Widget options structure has been changed.

---

build.gradle
src/main/java/com/epam/ta/reportportal/core/configs/WidgetConfig.java
src/main/java/com/epam/ta/reportportal/core/launch/GetLaunchHandler.java
src/main/java/com/epam/ta/reportportal/core/launch/impl/GetLaunchHandler.java
src/main/java/com/epam/ta/reportportal/core/widget/content/constant/ContentLoaderConstants.java
src/main/java/com/epam/ta/reportportal/core/widget/content/filter/ProductStatusFilterStrategy.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/AbstractStatisticsContentLoader.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/ActivityContentLoader.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/BugTrendChartContentLoader.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/CasesTrendContentLoader.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/ChartInvestigatedContentLoader.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/FlakyCasesTableContentLoader.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/LaunchStatisticsChartContentLoader.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/LaunchesComparisonContentLoader.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/MostTimeConsumingContentLoader.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/OverallStatisticsContentLoader.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/PassingRatePerLaunchContentLoader.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/PassingRateSummaryContentLoader.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/ProductStatusFilterGroupedContentLoader.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/ProductStatusLaunchGroupedContentLoader.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/TopTestCasesContentLoader.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/util/FilterUtils.java
src/main/java/com/epam/ta/reportportal/core/widget/util/WidgetOptionUtil.java
src/main/java/com/epam/ta/reportportal/ws/controller/LaunchController.java
src/main/java/com/epam/ta/reportportal/ws/converter/converters/LaunchConverter.java
src/test/java/com/epam/ta/reportportal/core/widget/util/WidgetOptionUtilTest.java

Widgets query builder migration api

---

build.gradle
src/main/java/com/epam/ta/reportportal/core/item/GetTestItemHandler.java
src/main/java/com/epam/ta/reportportal/core/item/impl/GetTestItemHandlerImpl.java
src/main/java/com/epam/ta/reportportal/core/launch/impl/GetLaunchHandler.java
src/main/java/com/epam/ta/reportportal/ws/controller/TestItemController.java

[EPMRPP-37301] Update constants in filter
[EPMRPP-37302] Get unique launch names
[EPMRPP-37303] Get owner logins instead full names
[EPMRPP-37066] Contains ignore case
[EPMRPP-37321] Add filter mode validation
[EPMRPP-37279] Getting items by filter validation

[EPMRPP-37301], [EPMRPP-37302], [EPMRPP-37303], [EPMRPP-37066], [EPMRPP-37321], [EPMRPP-37279] Bugfix

---

build.gradle
src/main/java/com/epam/ta/reportportal/core/activity/ActivityHandler.java
src/main/java/com/epam/ta/reportportal/core/analyzer/impl/LogIndexerService.java
src/main/java/com/epam/ta/reportportal/core/analyzer/strategy/ManuallyAnalyzedCollector.java
src/main/java/com/epam/ta/reportportal/core/item/GetTestItemHandler.java
src/main/java/com/epam/ta/reportportal/core/item/impl/DeleteTestItemHandlerImpl.java
src/main/java/com/epam/ta/reportportal/core/item/impl/StartTestItemHandlerImpl.java
src/main/java/com/epam/ta/reportportal/core/item/impl/UpdateTestItemHandlerImpl.java
src/main/java/com/epam/ta/reportportal/core/launch/impl/DeleteLaunchHandlerImpl.java
src/main/java/com/epam/ta/reportportal/core/launch/impl/GetLaunchHandlerImpl.java
src/main/java/com/epam/ta/reportportal/core/launch/impl/UpdateLaunchHandlerImpl.java
src/test/java/com/epam/ta/reportportal/core/item/impl/DeleteTestItemHandlerImplTest.java

MERGE AFTER https://github.com/reportportal/service-api/pull/663

EPMRPP-38208 || Performance optimization api

---

build.gradle
src/main/java/com/epam/ta/reportportal/ws/resolver/FilterCriteriaResolver.java

EPMRPP-38660 || Validation for empty filter value has been provided.

---

src/main/java/com/epam/ta/reportportal/core/integration/util/EmailServerIntegrationService.java
src/main/java/com/epam/ta/reportportal/util/email/EmailService.java
src/main/resources/templates/email/email-connection.ftl

EPMRPP-38888 || Email integration connection test fix

---

build.gradle

Service API module uses commons-dao and commons-model libraries that were modified during the SAML integration implementation.

SAML integration: aligned libraries version

---

build.gradle
src/main/java/com/epam/ta/reportportal/core/hierarchy/AbstractFinishHierarchyHandler.java
src/main/java/com/epam/ta/reportportal/core/item/impl/FinishTestItemHandlerImpl.java
src/test/java/com/epam/ta/reportportal/ws/controller/WidgetControllerTest.java

MERGE AFTER
https://github.com/reportportal/service-api/pull/799

Nested items quering fix api

---

src/main/java/com/epam/ta/reportportal/core/configs/EmailConfiguration.java
src/main/java/com/epam/ta/reportportal/core/configs/ExternalSystemsConfiguration.java
src/main/java/com/epam/ta/reportportal/core/item/impl/history/TestItemsHistoryService.java
src/main/java/com/epam/ta/reportportal/core/user/CreateUserHandler.java
src/main/java/com/epam/ta/reportportal/core/user/DeleteUserHandler.java
src/main/java/com/epam/ta/reportportal/exception/DataStorageException.java
src/main/java/com/epam/ta/reportportal/exception/HandlerNotDefinedException.java
src/main/java/com/epam/ta/reportportal/exception/PermissionNotDefinedException.java
src/main/java/com/epam/ta/reportportal/exception/UserAccountExpiredException.java
src/main/java/com/epam/ta/reportportal/util/ApplicationContextAwareFactoryBean.java
src/main/java/com/epam/ta/reportportal/util/ResourceCopierBean.java
src/main/java/com/epam/ta/reportportal/util/SystemInformatorService.java
src/main/java/com/epam/ta/reportportal/ws/converter/PagedResourcesAssembler.java
src/main/java/com/epam/ta/reportportal/ws/converter/builders/Builder.java
src/main/java/com/epam/ta/reportportal/ws/resolver/ActiveRole.java
src/main/java/com/epam/ta/reportportal/ws/resolver/ActiveUserWebArgumentResolver.java
src/main/java/com/epam/ta/reportportal/ws/resolver/FilterFor.java
src/main/java/com/epam/ta/reportportal/ws/resolver/JacksonViewAware.java
src/main/java/com/epam/ta/reportportal/ws/resolver/JacksonViewAwareModule.java
src/main/java/com/epam/ta/reportportal/ws/resolver/JacksonViewReturnValueHandler.java
src/main/java/com/epam/ta/reportportal/ws/resolver/JsonViewSupportFactoryBean.java
src/main/java/com/epam/ta/reportportal/ws/resolver/ResponseView.java
src/main/java/com/epam/ta/reportportal/ws/resolver/SortFor.java
src/main/java/com/epam/ta/reportportal/ws/validation/JaskonRequiredPropertiesValidator.java
src/test/java/com/epam/ta/reportportal/auth/UserRoleHierarchyTest.java
src/test/java/com/epam/ta/reportportal/ws/validation/BusinessRuleTest.java

Signed-off-by: avarabyeu <andrei.varabyeu@gmail.com>

Fix license headers

---

src/main/java/com/epam/ta/reportportal/core/configs/rabbit/InternalConfiguration.java
src/main/java/com/epam/ta/reportportal/core/events/MessageBusImpl.java
src/main/java/com/epam/ta/reportportal/ws/rabbit/ActivityConsumer.java
src/test/java/com/epam/ta/reportportal/ws/rabbit/ActivityConsumerTest.java

Replace direct exchange with topic exchange in order to support routing keys

Send built activity over rabbit

---

docker/Dockerfile-dev-release
docker/Dockerfile-release

Fixing environment variables override in start.sh generated in docker files

Fixing environment variables override

---

src/main/java/com/epam/ta/reportportal/core/item/GetTestItemHandler.java
src/main/java/com/epam/ta/reportportal/core/item/impl/GetTestItemHandlerImpl.java
src/main/java/com/epam/ta/reportportal/core/launch/GetLaunchHandler.java
src/main/java/com/epam/ta/reportportal/core/launch/impl/GetLaunchHandlerImpl.java
src/main/java/com/epam/ta/reportportal/core/log/GetLogHandler.java
src/main/java/com/epam/ta/reportportal/core/log/impl/GetLogHandlerImpl.java
src/main/java/com/epam/ta/reportportal/ws/controller/LaunchController.java
src/main/java/com/epam/ta/reportportal/ws/controller/LogController.java
src/main/java/com/epam/ta/reportportal/ws/controller/TestItemController.java
src/main/resources/application.yaml
src/test/java/com/epam/ta/reportportal/core/item/impl/GetTestItemHandlerImplTest.java
src/test/java/com/epam/ta/reportportal/core/launch/impl/GetLaunchHandlerImplTest.java
src/test/java/com/epam/ta/reportportal/ws/controller/LaunchControllerTest.java
src/test/java/com/epam/ta/reportportal/ws/controller/LogControllerTest.java
src/test/java/com/epam/ta/reportportal/ws/controller/TestItemControllerTest.java

fixes [#782](https://github.com/reportportal/reportportal/issues/782)

Support v4 get rq by string id

---

build.gradle
src/main/java/com/epam/ta/reportportal/core/events/handler/ComponentHealthCheckTableEventHandler.java
src/main/java/com/epam/ta/reportportal/core/events/widget/GenerateComponentHealthCheckTableEvent.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/util/healthcheck/AbstractHealthCheckTableContentResolver.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/util/healthcheck/HealthCheckTableCreatedContentResolver.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/util/healthcheck/HealthCheckTableRefreshContentResolver.java
src/main/java/com/epam/ta/reportportal/core/widget/content/loader/util/healthcheck/util/HealthCheckTableGenerator.java

MERGE AFTER https://github.com/reportportal/service-api/pull/1293

EPMRPP-56108 || Health check table content generation fix

---

src/main/java/com/epam/ta/reportportal/core/filter/impl/UpdateUserFilterHandlerImpl.java
src/main/java/com/epam/ta/reportportal/core/widget/impl/GetWidgetHandlerImpl.java

Widget-filter relation removing fix

EPMRPP-42018 || Sharing/unsharing behaviour for filter fix. 

---

build.gradle

Fixes reportportal/reportportal#1050

[EPMRPP-54190] - Add UUID data to TestItem Controller when querying using filters 

---

build.gradle
src/main/java/com/epam/ta/reportportal/core/item/identity/IdentityUtil.java
src/main/java/com/epam/ta/reportportal/core/item/identity/TestCaseHashGenerator.java
src/main/java/com/epam/ta/reportportal/core/item/identity/TestCaseHashGeneratorImpl.java
src/main/java/com/epam/ta/reportportal/core/item/identity/TestItemUniqueIdGenerator.java
src/main/java/com/epam/ta/reportportal/core/item/identity/UniqueIdGenerator.java
src/main/java/com/epam/ta/reportportal/core/item/impl/StartTestItemHandlerImpl.java
src/main/java/com/epam/ta/reportportal/core/item/impl/merge/strategy/AbstractLaunchMergeStrategy.java
src/main/java/com/epam/ta/reportportal/core/launch/rerun/RerunHandlerImpl.java
src/main/java/com/epam/ta/reportportal/ws/converter/builders/TestCaseIdEntry.java
src/main/java/com/epam/ta/reportportal/ws/converter/builders/TestItemBuilder.java
src/test/java/com/epam/ta/reportportal/core/item/impl/TestCaseHashGeneratorImplTest.java
src/test/java/com/epam/ta/reportportal/core/item/impl/TestItemUniqueIdGeneratorTest.java
src/test/java/com/epam/ta/reportportal/core/launch/rerun/RerunHandlerImplTest.java

https://github.com/reportportal/reportportal/issues/980
https://github.com/reportportal/reportportal/issues/880

EPMRPP-57313 || EPMRPP-52038 || Re-runs logic updated based on `testCaseHash`

---

build.gradle

Epmrpp 59597

---

build.gradle

update dao artifact version

---

build.gradle

update commons-dao version

---

build.gradle
src/main/java/com/epam/ta/reportportal/core/log/impl/GetLogHandlerImpl.java

Add projectId filter to log filter

Add projectId filter to log filter

---

src/main/java/com/epam/ta/reportportal/core/events/handler/subscriber/impl/LaunchAutoAnalysisSubscriber.java

Process AutoAnalyzer sync

---

src/main/java/com/epam/ta/reportportal/core/events/handler/subscriber/impl/LaunchAutoAnalysisSubscriber.java
src/test/java/com/epam/ta/reportportal/core/events/handler/subscriber/impl/LaunchAutoAnalysisSubscriberTest.java

Move from async to sync process auto analyzer

Move from async to sync process auto analyzer

---

src/main/java/com/epam/ta/reportportal/core/events/handler/subscriber/impl/LaunchAutoAnalysisSubscriber.java
src/test/java/com/epam/ta/reportportal/core/events/handler/subscriber/impl/LaunchAutoAnalysisSubscriberTest.java

Revert analyzer/index changes

---

src/main/java/com/epam/ta/reportportal/core/analyzer/auto/strategy/search/FilterCollector.java

EPMRPP-60755 || Fix analyzer request

Fix analyzer request

---

src/main/java/com/epam/ta/reportportal/core/configs/IntegrationConfig.java
src/main/java/com/epam/ta/reportportal/core/integration/util/AzureIntegrationService.java
src/test/java/com/epam/ta/reportportal/core/integration/util/AzureIntegrationServiceTest.java

Added support for azure plugin.

EPMRPP-64822: Add AzureIntegrationService

---

src/main/java/com/epam/ta/reportportal/core/analyzer/auto/impl/SuggestItemService.java

Make decision modal. Similarity percent values in "ML suggestions" tabs has extra digits for floating numbers

EPMRPP-69114 || Make decision modal. Similarity percent values in "ML suggestions" tabs has extra digits for floating numbers

---

src/main/java/com/epam/ta/reportportal/core/configs/remover/ContentRemoverConfig.java
src/main/java/com/epam/ta/reportportal/core/remover/user/UserContentRemover.java
src/main/java/com/epam/ta/reportportal/core/remover/user/UserPhotoRemover.java
src/main/java/com/epam/ta/reportportal/core/user/impl/DeleteUserHandlerImpl.java
src/test/java/com/epam/ta/reportportal/core/remover/user/UserContentRemoverTest.java
src/test/java/com/epam/ta/reportportal/core/remover/user/UserPhotoRemoverTest.java
src/test/java/com/epam/ta/reportportal/core/user/impl/DeleteUserHandlerImplTest.java

Realized user photo remover, removed datastore dependency

EPMRPP-65572 ||  Error on deleting user with photo when minio is stopped

---

src/main/java/com/epam/ta/reportportal/core/jasper/TestItemPojo.java

Launch export. Empty file is exported if there is item with 'in progress' status in the launch

EPMRPP-79208 || Empty file is exported.

---

build.gradle
src/main/java/com/epam/ta/reportportal/ws/converter/converters/ProjectSettingsConverter.java
src/test/java/com/epam/ta/reportportal/ws/converter/converters/UserConverterTest.java

Related PR:
https://github.com/reportportal/commons-model/pull/322/files
https://github.com/reportportal/commons-dao/pull/844/files

EPMRPP-78912 || Add project key to ProjectInfo

---

src/main/java/com/epam/ta/reportportal/demodata/DemoDataController.java

Request /v1/demo/item call endpoint for demo data generation not test item creation

EPMRPP-81046 || Impossible to report test items to project with "demo" name

---

src/main/resources/templates/email/index-finished-template.ftl

EPMRPP-82375 || Implement notification when changing password and make some templ. updates

---

src/main/java/com/epam/ta/reportportal/core/imprt/impl/junit/XunitImportHandler.java
src/test/java/com/epam/ta/reportportal/core/imprt/impl/junit/XunitImportHandlerTest.java

https://jiraeu.epam.com/browse/EPMRPP-85806
* added handling of timestamps with offset
* timestamps considered in UTC format
* test covered by different test cases

EPMRPP-85806 || added timestamps with offsets handling

---

build.gradle
src/main/java/com/epam/ta/reportportal/core/imprt/ImportLaunchHandlerImpl.java
src/test/java/com/epam/ta/reportportal/core/imprt/ImportLaunchHandlerImplTest.java
src/test/java/com/epam/ta/reportportal/util/sample/LaunchSampleUtil.java

https://jiraeu.epam.com/browse/EPMRPP-86742
* extended response for launch import

EPMRPP-86742 || extended launch import response

---

src/main/java/com/epam/ta/reportportal/core/imprt/ImportLaunchHandlerImpl.java

https://jiraeu.epam.com/browse/EPMRPP-86542

EPMRPP-86742 || message fix

---

src/main/java/com/epam/ta/reportportal/core/events/activity/AssignUserEvent.java
src/main/java/com/epam/ta/reportportal/core/events/activity/UnassignUserEvent.java
src/main/java/com/epam/ta/reportportal/core/events/activity/UserCreatedEvent.java
src/main/java/com/epam/ta/reportportal/core/events/activity/util/ActivityDetailsUtil.java
src/main/java/com/epam/ta/reportportal/core/project/ProjectUserHandler.java
src/main/java/com/epam/ta/reportportal/core/project/impl/CreateProjectHandlerImpl.java
src/main/java/com/epam/ta/reportportal/core/project/impl/DeleteProjectHandlerImpl.java
src/main/java/com/epam/ta/reportportal/core/project/impl/ProjectUserHandlerImpl.java
src/main/java/com/epam/ta/reportportal/core/project/impl/UpdateProjectHandlerImpl.java
src/main/java/com/epam/ta/reportportal/core/user/impl/CreateUserHandlerImpl.java
src/test/java/com/epam/ta/reportportal/core/events/activity/UserCreatedEventTest.java

* changed activity parameters upon creating invited user
* activity parameters in case of creating user by admin remain the same

EPMRPP-86466 || changed activity parameters upon creating invited user

---

src/main/java/com/epam/ta/reportportal/info/JobsInfoContributor.java

EPMRPP-87596 || No possibility to switch on/off AA and Unique Errors from UI

---

src/main/java/com/epam/ta/reportportal/core/item/impl/FinishTestItemHandlerImpl.java
src/test/java/com/epam/ta/reportportal/core/item/impl/FinishTestItemHandlerImplTest.java

Reverts reportportal/service-api#2030

Revert "EPMRPP-92613 || Remove empty status verifier for suite"

---

src/main/java/com/epam/ta/reportportal/core/project/impl/UpdateProjectHandlerImpl.java
src/main/java/com/epam/ta/reportportal/ws/controller/OrganizationController.java
src/main/java/com/epam/ta/reportportal/ws/controller/OrganizationProjectController.java
src/main/java/com/epam/ta/reportportal/ws/controller/OrganizationUsersController.java

- updated api specification
- added assign organization to the flow

EPMRPP-91633 update user assign flow

---

src/main/resources/application.properties

use full qualified names in swagger doc config

EPMRPP-93697 fix same filename overwrites class

---

build.gradle
src/main/java/com/epam/ta/reportportal/core/user/impl/CreateUserHandlerImpl.java
src/main/java/com/epam/ta/reportportal/model/user/CreateUserRS.java

Add UUID and other essential fields.

Expand existing user creation response

---

src/main/java/com/epam/ta/reportportal/model/project/ProjectResource.java
src/main/java/com/epam/ta/reportportal/ws/converter/converters/ProjectConverter.java

Added fields:
- accountRole;
- accountType;

Update ProjectResource model to expand project user response.

---

.github/workflows/java-checks.yml
src/main/java/com/epam/ta/reportportal/core/integration/util/EmailServerIntegrationService.java
src/main/java/com/epam/ta/reportportal/util/email/EmailService.java

- Separated the logic for creating and deleting SMTP notifications
- Refactored code for better readability and maintainability

Split SMTP creation and deletion notifications logic

---

src/main/java/com/epam/ta/reportportal/core/analyzer/config/PatternAnalysisRabbitConfiguration.java
src/main/java/com/epam/ta/reportportal/core/configs/rabbit/BackgroundProcessingConfiguration.java
src/main/java/com/epam/ta/reportportal/core/configs/rabbit/InternalConfiguration.java
src/main/java/com/epam/ta/reportportal/reporting/async/config/ReportingTopologyConfiguration.java

Reverts reportportal/service-api#2146

Revert "EPMRPP-98822 || Change queues from classic to quorum."

---

src/main/java/com/epam/ta/reportportal/core/project/impl/UpdateProjectHandlerImpl.java

EPMRPP-99369 || "Slack" toggle state is not preserved on a new project after reloading the page

---

.github/workflows/build-dev-image.yml
build.gradle

This pull request updates the submodule reference for the `api-registry` subproject to point to the latest commit.
* [`api-registry`](diffhunk://#diff-e8d2247ee9aa857989a6e07bc040a6e5e26ca1223e0f13523002a05968708e9cL1-R1): Updated the submodule commit reference to `4782332e0d13d897405dab981aa4a93d101882e2`.

EPMRPP-101153 || Group statistics

---

.github/workflows/drill-checks.yml

Update drill-checks.yml to send test information to the Drill4J during push events

---

gradle/libs.versions.toml
project-properties.gradle
src/main/java/com/epam/ta/reportportal/core/organization/impl/GetOrganizationHandlerImpl.java
src/main/java/com/epam/ta/reportportal/ws/converter/converters/OrganizationConverter.java

This pull request introduces updates to dependency versions, refactors a key handler class to simplify its implementation, and modifies database migration mappings. The most significant changes include updating the `commons-dao-dev` version, removing unused imports and parameters from the `GetOrganizationHandlerImpl` class, and updating database migration references.

EPMRPP-105306 || update organizations mapping

---

src/main/resources/templates/report/report.jrxml

This PR addresses the following issues:
- Removes an extra comma in the `duration` field
- Ensures attachments are properly included in the `type` field

EPMRPP-107175 || Launches report fixes

---

gradle/libs.versions.toml
src/main/java/com/epam/ta/reportportal/core/events/activity/OrganizationCreatedEvent.java
src/main/java/com/epam/ta/reportportal/core/events/activity/OrganizationDeletedEvent.java
src/main/java/com/epam/ta/reportportal/core/events/activity/OrganizationUpdatedEvent.java
src/main/java/com/epam/ta/reportportal/core/organization/OrganizationExtensionPoint.java
src/main/java/com/epam/ta/reportportal/model/activity/OrganizationAttributesActivityResource.java
src/main/java/com/epam/ta/reportportal/ws/controller/OrganizationController.java
src/test/java/com/epam/ta/reportportal/core/events/activity/OrganizationCreatedEventTest.java
src/test/java/com/epam/ta/reportportal/core/events/activity/OrganizationDeletedEventTest.java
src/test/java/com/epam/ta/reportportal/core/events/activity/OrganizationUpdatedEventTest.java

This pull request introduces new event classes and related tests to support activity tracking for organization lifecycle changes (creation, update, deletion). It also refactors the organization management API to require user context for these operations and updates dependencies. The main themes are improved activity auditing and API security.
**Activity Tracking Enhancements**
* Added new event classes: `OrganizationCreatedEvent`, `OrganizationUpdatedEvent`, and `OrganizationDeletedEvent`, each converting organization lifecycle actions into structured `Activity` objects for audit logging. [[1]](diffhunk://#diff-1b8d94a6680c77122211cb985ad28b9f4248f742946194b4aec2cb477775687dR1-R72) [[2]](diffhunk://#diff-169ce9e22a22bf06221898cc62e1ad15da9ad8fba64c5442c420346d7bc95fffR1-R84) …

EPMRPP-104711 || Organization CRUD events

---

build.gradle
src/main/java/com/epam/ta/reportportal/core/item/impl/GetTestItemHandlerImpl.java
src/main/java/com/epam/ta/reportportal/ws/converter/utils/item/provider/NestedStepsUpdaterProvider.java
src/main/java/com/epam/ta/reportportal/ws/converter/utils/item/updater/NestedStepsUpdater.java
src/test/java/com/epam/ta/reportportal/core/item/impl/GetTestItemHandlerImplTest.java

Depends on:
https://github.com/reportportal/commons-reporting/pull/22
https://github.com/reportportal/commons/pull/67
https://github.com/reportportal/commons-dao/pull/1157

EPMRPP-107835 || Update get item endpoint to return hasNestedSteps flag

---

src/main/java/com/epam/ta/reportportal/core/launch/impl/UpdateLaunchHandlerImpl.java
src/test/java/com/epam/ta/reportportal/core/launch/impl/UpdateLaunchHandlerImplTest.java

This PR updates validation for PUT/v1/{projectName}/launch/{launchId}/update and allows customer to update the lauch mode (own/not own)

EPMRPP-107873 || Customer can change launch mode
